spring:
  datasource:
    url:  jdbc:h2:file:${user.dir}/data/s13;CACHE_SIZE=8192;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE #jdbc:h2:C:\Users\bsagar8\sagarapidev\s13\data\s13
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update

  h2:
    console.settings.trace: false
    console.settings.web-allow-others: false






